spring.application.name=farmer

#??? ??????????? ? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/farmer_market_db
spring.datasource.username=postgres
spring.datasource.password=mamaImama123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#??? ???????????? ??????
server.error.include-message=always
server.error.include-binding-errors=always

# === ????????? ??? YANDEX ===
spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=mihamalorodov009@yandex.ru
spring.mail.password=krjdzaiisyucxfuc
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.yandex.ru
# spring.mail.properties.mail.debug=true

# ???????????? ?????? ?????? ?????
spring.servlet.multipart.max-file-size=10MB
# ???????????? ????? ?????? ??????? (??? ???? + JSON)
spring.servlet.multipart.max-request-size=30MB

