spring.application.name=farmer

#??? ??????????? ? ??
spring.datasource.url=jdbc:postgresql://localhost:5432/farmer_market_db
spring.datasource.username=postgres
spring.datasource.password=mamaImama123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#??? ???????????? ??????
server.error.include-message=always
server.error.include-binding-errors=always

#??? ???????? ???? ?? ?????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=malorodov7@gmail.com
spring.mail.password=urvicqivteatquna
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ???????????? ?????? ?????? ?????
spring.servlet.multipart.max-file-size=10MB
# ???????????? ????? ?????? ??????? (??? ???? + JSON)
spring.servlet.multipart.max-request-size=30MB

